#!/bin/bash

set -e

FLE='/etc/chromium/master_preferences'
if [ -e "$FLE" ] && [ ! -e "$FLE.divert" ]; then
  dpkg-divert --add --rename --divert $FLE.divert $FLE
  if [ -e "$FLE" ]; then
      rm "$FLE"
  fi
fi

#DEBHELPER#
